spring:  
  application:
    name: service-configuration  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/malet-pr/microservicesExample/service-configuration
          clone-on-start: true

server:
  port: 8888
  
  